package com.supergroup.core.constant;

import java.util.Arrays;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import org.apache.commons.lang3.StringUtils;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@Getter
@AllArgsConstructor
@ToString
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum ErrorCode {
    // SERVER CODE from 1000 - 1999, define carefully
    SERVER_ERROR("SERVER_ERROR", "Server internal error"),
    TOKEN_EXPIRED("TOKEN_EXPIRED", "The token has expired."),
    EMAIL_IS_EXISTED("EMAIL_IS_EXISTED", "Oops! seems like your email already registered for our services before"),
    OTP_IS_INCORRECT("OTP_IS_INCORRECT", "OTP is incorrect."),
    USER_IS_VERIFYING("USER_IS_VERIFYING", "Your registration is being process, please check your email and follow the instructions"),
    PASSWORD_IS_WRONG("PASSWORD_IS_WRONG", "Password is incorrect."),
    USER_NOT_FOUND("USER_NOT_FOUND", "User not found."),
    UNAUTHORIZED("UNAUTHORIZED", "Unauthorized!"),
    CURRENT_PASSWORD_IS_WRONG("CURRENT_PASSWORD_IS_WRONG", "Current password is incorrect."),
    OTP_NOT_VALID("OTP_NOT_VALID", "Otp is not valid"),
    VERIFY_REASON_INVALID("VERIFY_REASON_INVALID", "Invalid verify reason"),
    VERIFY_ATTEMPT_EXCEEDED("VERIFY_ATTEMPT_EXCEEDED",
                            "Verify session attempt has been exceeded You have enterd in correctly more than 3 times. Please signup again"),
    BAD_REQUEST_ERROR("BAD_REQUEST_ERROR", "Oops Something went wrong. The server can not process your request. Please try it later"),
    REGISTRATION_SESSION_NOT_FOUND("REGISTRATION_SESSION_NOT_FOUND", "Can't found any appropriate registration session"),
    USER_IS_LOGGED_OUT("USER_IS_LOGGED_OUT", "User was logged out"),
    UPDATE_USER_INFO_FAILED("UPDATE_USER_INFO_FAILED", "Oops! Something went wrong when updating your account. Please try again later"),
    NEW_PASSWORD_HAS_NO_CHANGE("NEW_PASSWORD_HAS_NO_CHANGE", "Please enter by password different from your current password"),
    NEW_EMAIL_HAS_NO_CHANGE("NEW_EMAIL_HAS_NO_CHANGE", "Please enter by email different from your current email"),
    STATUS_NOT_VALID("STATUS_NOT_VALID", "User status is not valid"),
    USER_PROFILE_NOT_FOUND("USER_PROFILE_NOT_FOUND", "User profile not found"),
    CONFIG_NOT_FOUND("CONFIG_NOT_FOUND", "Config not found"),
    CAN_NOT_SEND_EMAIL("CAN_NOT_SEND_EMAIL", "Oops! Something went wrong. Can't send email to you. Please try again later"),
    RESET_METHOD_INVALID("RESET_METHOD_INVALID", "Reset password method is invalid"),
    VERIFY_SESSION_INVALID("VERIFY_SESSION_INVALID", "Can't found any appropriate verify session belong to you"),
    RESET_PASSWORD_TOKEN_EXPIRED("RESET_PASSWORD_TOKEN_EXPIRED", "Reset password session is expired"),
    REQUEST_CREATE_VERIFY_INVALID("REQUEST_CREATE_VERIFY_INVALID",
                                  "The request to create a verification session is being processed, please check your email to get a code or retry after 1 minute"),
    CANNOT_CREATE_TOKEN("CANNOT_CREATE_TOKEN", "Server cannot create token"),
    USER_MUST_REGISTER_NOTIFY("USER_MUST_REGISTER_NOTIFY", "User must register notify"),
    CANNOT_SEND_NOTIFICATION("CANNOT_SEND_NOTIFICATION", "Can not send notification"),
    VERIFY_SESSION_EXPIRED("VERIFY_SESSION_EXPIRED", "Verify session is expired"),
    TOO_MANY_WRONG_LOGIN("TOO_MANY_WRONG_LOGIN", "Too many incorrect logins, please try again later"),
    STATUS_NOT_FOUND("STATUS_NOT_FOUND", "Status not found"),
    USER_WAS_DELETED_OR_BANNED("USER_WAS_DELETED_OR_BANNED", "User was deleted or banned"),

    // KOS_BUILDING
    KOS_PROFILE_NOT_FOUND("KOS_PROFILE_NOT_FOUND", "Kos profile not found"),
    KOS_PROFILE_ALREADY_EXISTS("KOS_PROFILE_ALREADY_EXISTS", "Kos profile already exist"),
    CASTLE_BUILDING_NOT_FOUND("CASTLE_BUILDING_NOT_FOUND", "Castle building not found"),
    VAULT_BUILDING_IS_NOT_FOUND("VAULT_BUILDING_IS_NOT_FOUND", "Vault building is not found"),
    LIGHTHOUSE_BUILDING_IS_NOT_FOUND("LIGHTHOUSE_BUILDING_IS_NOT_FOUND", "Lighthouse building is not found"),
    KOS_ASSETS_NOT_FOUND("KOS_ASSETS_NOT_FOUND", "Kos assets not found"),
    KOS_POINTS_NOT_FOUND("KOS_POINTS_NOT_FOUND", "Kos points not found"),
    CASTLE_BUILDING_CONFIG_NOT_FOUND("CASTLE_BUILDING_CONFIG_NOT_FOUND", "Castle building config not found"),
    CAN_NOT_UPGRADE_BECAUSE_NOT_FOUND_NEXT_LEVEL("CAN_NOT_UPGRADE_BECAUSE_NOT_FOUND_NEXT_LEVEL",
                                                 "You have reached max level"),
    DO_NOT_MEET_RESOURCE_REQUIREMENT("DO_NOT_MEET_RESOURCE_REQUIREMENT", "You do not meet resource requirement"),
    BUILDING_IS_IN_OTHER_PROCESS("BUILDING_IS_IN_OTHER_PROCESS", "Building is in other process"),
    CONFIG_LEVEL_NOT_FOUND("CONFIG_LEVEL_NOT_FOUND", "Config level not found"),
    BUILDING_NOT_IN_UPGRADING("BUILDING_NOT_IN_UPGRADING", "The bulding is not in upgrading process"),

    USER_TECHNOLOGY_NOT_FOUND("USER_TECHNOLOGY_NOT_FOUND", "User's techonology is not found"),

    RESEARCH_BUILDING_IS_NOT_FOUND("RESEARCH_BUILDING_IS_NOT_FOUND", "Research building is not found"),
    RESEARCH_BUILDING_CONFIG_IS_NOT_FOUND("RESEARCH_BUILDING_CONFIG_IS_NOT_FOUND", "Research building config is not found"),
    THE_FIRST_ELEMENT_REQUIRE_MINING_TYPE_FIRST("THE_FIRST_ELEMENT_REQUIRE_MINING_TYPE_FIRST", "the first element requires type first"),
    MINING_TYPE_NOT_FOUND("MINING_TYPE_NOT_FOUND", "Mining type not found"),
    SEA_MINING_SESSION_NOT_FOUND("SEA_MINING_SESSION_NOT_FOUND", "Sea mining session is not found"),
    WOOD_MINE_BUILDING_IS_NOT_FOUND("WOOD_MINE_BUILDING_IS_NOT_FOUND", "Wood mine bulding is not found"),
    FULLY_EXPLOITED("FULLY_EXPLOITED", "Fully exploited"),
    EXCEED_THE_ALLOWED_NUMBER_OF_PEOPLE("EXCEED_THE_ALLOWED_NUMBER_OF_PEOPLE", "exceed the allowed number of people"),
    NOT_ENOUGH_IDLE_POPULATION("NOT_ENOUGH_IDLE_POPULATION", "Not enough idle population"),
    SUCCESSFUL_UPGRADE_TIME_MUST_BE_AFTER_THE_CURRENT_TIME("SUCCESSFUL_UPGRADE_TIME_MUST_BE_AFTER_THE_CURRENT_TIME",
                                                           "Successful upgrade time must be after the current time"),
    AMOUNT_CONVERT_INVALID("AMOUNT_CONVERT_INVALID", "Amount convert is invalid"),
    STORAGE_BUILDING_NOT_FOUND("STORAGE_BUILDING_NOT_FOUND", "Storage building is not found"),
    VAULT_BUILDING_CONFIG_IS_NOT_FOUND("VAULT_BUILDING_CONFIG_IS_NOT_FOUND", "Vault building config is not found"),
    NUMBER_OF_QUEEN_CARD_IS_INVALID("NUMBER_OF_QUEEN_CARD_IS_INVALID", "Number of queen card is invalid"),
    QUEEN_MODEL_NOT_FOUND("QUEEN_MODEL_NOT_FOUND", "Queen model is not found"),
    QUEEN_BUILDING_IS_NOT_FOUND("QUEEN_BUILDING_IS_NOT_FOUND", "Queen building is not found"),
    COMMUNITY_BUILDING_IS_NOT_FOUND("COMMUNITY_BUILDING_IS_NOT_FOUND", "Community building is not found"),
    COMMUNITY_BUILDING_CONFIG_IS_NOT_FOUND("COMMUNITY_BUILDING_CONFIG_IS_NOT_FOUND", "Community building config is not found"),
    RELIC_NOT_FOUND("RELIC_NOT_FOUND", "Relic is not found"),
    RELIC_IS_LISTING("RELIC_IS_LISTING", "Relic is listing"),
    RELIC_IS_NOT_LISTING("RELIC_NOT_IS_LISTING", "Relic is not listing"),
    RELIC_SLOT_LISTING_IS_FULL("RELIC_SLOT_LISTING_IS_FULL", "Showed Relics Slots are full"),
    QUEEN_BUILDING_CONFIG_IS_NOT_FOUND("QUEEN_BUILDING_CONFIG_IS_NOT_FOUND", "Queen building config is not found"),
    NOT_ENOUGH_SPACE_TO_LISTING_RELIC("NOT_ENOUGH_SPACE_TO_LISTING_RELIC", "Not enough space to listing"),
    RELIC_LEVEL_IS_TOO_HIGH("RELIC_LEVEL_IS_TOO_HIGH", "Relic level is too high"),
    RELIC_MODEL_NOT_FOUND("RELIC_MODEL_NOT_FOUND", "Relic model not found"),
    QUEEN_NOT_FOUND("QUEEN_NOT_FOUND", "Queen is not found"),
    STONE_MINE_BUILDING_IS_NOT_FOUND("STONE_MINE_BUILDING_IS_NOT_FOUND", "Stone mine building is not found"),
    PEOPLE_MUST_BE_LARGER_THAN_IN_THE_MINES("PEOPLE_MUST_BE_LARGER_THAN_IN_THE_MINES", "People must be larger than in the mines"),
    COMMAND_BUILDING_IS_NOT_FOUND("COMMAND_BUILDING_IS_NOT_FOUND", "Command building is not found"),
    COMMAND_BUILDING_CONFIG_IS_NOT_FOUND("COMMAND_BUILDING_CONFIG_IS_NOT_FOUND", "Command building config is not found"),
    MOTHER_SHIP_IS_NOT_FOUND("MOTHER_SHIP_IS_NOT_FOUND", "Mother ship is not found"),
    MOTHER_SHIP_LEVEL_CONFIG_IS_NOT_FOUND("MOTHER_SHIP_LEVEL_CONFIG_IS_NOT_FOUND", "Mother ship level config is not found"),
    CAN_NOT_UPGRADE_BECAUSE_THE_MAX_ALLOWED_LEVEL("CAN_NOT_UPGRADE_BECAUSE_THE_MAX_ALLOWED_LEVEL", "Can not upgrade because the max allowed level"),
    MOTHER_SHIP_IS_IN_OTHER_PROCESS("MOTHER_SHIP_IS_IN_OTHER_PROCESS", "Mother ship is in other process!"),
    WEAPON_IS_NOT_FOUND("WEAPON_IS_NOT_FOUND", "Weapon is not found"),
    WEAPON_SET_IS_NOT_FOUND("WEAPON_SET_IS_NOT_FOUND", "Weapon set is not found"),
    WEAPON_SET_CONFIG_IS_NOT_FOUND("WEAPON_SET_CONFIG_IS_NOT_FOUND", "Weapon set config is not found"),
    NOT_ENOUGH_WEAPON("NOT_ENOUGH_WEAPON", "Not enough weapon"),
    RESEARCH_BUILDING_IS_NOT_LEVEL_ENOUGH("RESEARCH_BUILDING_IS_NOT_LEVEL_ENOUGH", "Research building is not level enough"),
    WEAPON_SET_LEVEL_CONFIG_IS_NOT_FOUND("WEAPON_SET_LEVEL_CONFIG_IS_NOT_FOUND", "Weapon set level config is not found"),
    ARMORY_BUILDING_IS_NOT_FOUND("ARMORY_BUILDING_IS_NOT_FOUND", "Armory building is not found"),
    ARMORY_BUILDING_CONFIG_IS_NOT_FOUND("ARMORY_BUILDING_CONFIG_IS_NOT_FOUND", "Armory building config is not found"),
    CAN_NOT_UPGRADE_BECAUSE_THE_LEVEL_IS_MAXED("CAN_NOT_UPGRADE_BECAUSE_THE_LEVEL_IS_MAXED", "Can not upgrade because the level is maxed"),
    ARMORY_BUILDING_IS_NOT_LEVEL_ENOUGH("ARMORY_BUILDING_IS_NOT_LEVEL_ENOUGH", "Armory building is not level enough"),
    ESCORT_SHIP_IS_NOT_FOUND("ESCORT_SHIP_IS_NOT_FOUND", "Guard ship is not found"),
    ESCORT_SHIP_GROUP_IS_NOT_FOUND("ESCORT_SHIP_GROUP_IS_NOT_FOUND", "Guard ship group is not found"),
    ESCORT_SHIP_GROUP_LEVEL_CONFIG_IS_NOT_FOUND("ESCORT_SHIP_GROUP_LEVEL_CONFIG_IS_NOT_FOUND", "Guard ship group level config is not found"),
    ESCORT_SHIP_GROUP_CONFIG_IS_NOT_FOUND("ESCORT_SHIP_GROUP_CONFIG_IS_NOT_FOUND", "Guard ship group config is not found"),
    DO_NOT_HAVE_ENOUGH_RESOURCE("DO_NOT_HAVE_ENOUGH_RESOURCE", "You don't have enough resources"),
    WEAPON_IS_EQUIPPING_ON_OTHER_MOTHER_SHIP("WEAPON_IS_EQUIPPING_ON_OTHER_MOTHER_SHIP", "Weapon is equipping on other mother ship"),
    MOTHER_SHIP_IS_EQUIPPED_FULL_WEAPON("MOTHER_SHIP_IS_EQUIPPED_FULL_WEAPON", "Mother ship is equipped full weapon"),
    WEAPON_IS_EQUIPPING_ON_THIS_MOTHER_SHIP("WEAPON_IS_EQUIPPING_ON_THIS_MOTHER_SHIP", "Weapon is equipping on this mother ship"),
    WEAPON_IS_NOT_EQUIPPING_ON_THIS_MOTHER_SHIP("WEAPON_IS_NOT_EQUIPPING_ON_THIS_MOTHER_SHIP", "Weapon is not equipping on this mother ship"),
    MOTHER_SHIP_QUALITY_CONFIG_IS_NOT_FOUND("MOTHER_SHIP_QUALITY_CONFIG_IS_NOT_FOUND", "Mother ship quality config is not found"),
    NOT_ENOUGH_MOTHER_SHIP_SLOT("NOT_ENOUGH_MOTHER_SHIP_SLOT",
                                "The mother ship slot is full. You need to upgrade the Command Port house level to increase the position of the mother ship"),
    MOTHER_SHIP_CONFIG_IS_NOT_FOUND("MOTHER_SHIP_CONFIG_IS_NOT_FOUND", "Mother ship config is not found"),
    WEAPON_IS_NOT_VALID("WEAPON_IS_NOT_VALID", "Weapon is not valid"),
    WEAPON_SET_IS_NOT_VALID("WEAPON_SET_IS_NOT_VALID", "Weapon set is not valid"),
    CAN_NOT_UPGRADE_BECAUSE_THE_MAX_ALLOWED_QUALITY("CAN_NOT_UPGRADE_BECAUSE_THE_MAX_ALLOWED_QUALITY",
                                                    "Can not upgrade because the max allowed quality"),
    CAN_NOT_UPGRADE_BECAUSE_WEAPON_SET_IS_EQUIPPING_ON_MOTHER_SHIP("CAN_NOT_UPGRADE_BECAUSE_WEAPON_SET_IS_EQUIPPING_ON_MOTHER_SHIP",
                                                                   "Can not upgrade because weapon set is equipping on mother ship"),
    CAN_NOT_UPGRADE_BECAUSE_WEAPON_IS_EQUIPPING_ON_MOTHER_SHIP("CAN_NOT_UPGRADE_BECAUSE_WEAPON_IS_EQUIPPING_ON_MOTHER_SHIP",
                                                               "Can not upgrade because weapon is equipping on mother ship"),
    NUMBER_OF_QUEEN_IS_MAXIMUM("NUMBER_OF_QUEEN_IS_MAXIMUM", "Number of Queen is maximum"),
    WEAPON_CONFIG_IS_NOT_FOUND("WEAPON_CONFIG_IS_NOT_FOUND", "Weapon Config is not found"),
    ESCORT_SHIP_CONFIG_IS_NOT_FOUND("ESCORT_SHIP_CONFIG_IS_NOT_FOUND", "Guard ship Config is not found"),
    MILITARY_BUILDING_IS_NOT_FOUND("MILITARY_BUILDING_IS_NOT_FOUND", "Military building is not found"),
    TITLE_IS_TOO_LONG("TITLE_IS_TOO_LONG", "Title is too long"),
    ESCORT_SHIP_GROUP_LEVEL_CONFIG_WRONG("ESCORT_SHIP_GROUP_LEVEL_CONFIG_WRONG", "Guard ship group level wrong"),
    RELIC_SLOT_AVAILABLE("RELIC_SLOT_AVAILABLE", "No Showed Relics Slot available. You can replace showed relics with another one"),
    TECHNOLOGY_NOT_FOUND("TECHNOLOGY_NOT_FOUND", "Technology not found"),
    CAN_NOT_CRAFT_BECAUSE_THE_TECHNOLOGY_IS_NOT_RESEARCHED("CAN_NOT_CRAFT_BECAUSE_THE_TECHNOLOGY_IS_NOT_RESEARCHED",
                                                           "Can not craft because the technology is not researched"),
    SCOUT_BUILDING_NOT_FOUND("SCOUT_BUILDING_NOT_FOUND", "Scout building not found"),
    SCOUT_BUILDING_CONFIG_IS_NOT_FOUND("SCOUT_BUILDING_CONFIG_IS_NOT_FOUND", "Scout building config is not found"),
    BUILDING_SCOUT_NOT_IN_TRAINING("BUILDING_SCOUT_NOT_IN_TRAINING", "The building scout is not in training process"),
    EXCEED_THE_MAXIMUM_NUMBER("EXCEED_THE_MAXIMUM_NUMBER", "Exceed the maximum number"),
    COMMAND_BUILDING_IS_NOT_LEVEL_ENOUGH("COMMAND_BUILDING_IS_NOT_LEVEL_ENOUGH", "Command building is not level enough"),
    SCOUT_CONFIG_NOT_FOUND("SCOUT_CONFIG_NOT_FOUND", "Scout config not found"),
    SCOUT_REPORT_NOT_FOUND("SCOUT_REPORT_NOT_FOUND", "Scout report not found"),
    SCOUT_NOT_FOUND("SCOUT_NOT_FOUND", "Scout not found"),
    NOT_ENOUGH_SOLDIERS("NOT_ENOUGH_SOLDIERS", "Not enough soldiers"),
    MISSION_TYPE_NOT_FOUND("MISSION_TYPE_NOT_FOUND", "Mission type is not found"),
    MISSION_TYPE_NOT_SUPPORTED("MISSION_TYPE_NOT_SUPPORTED", "Mission type is not supported"),
    NOT_ELIGIBLE_FOR_UPGRADE("NOT_ELIGIBLE_FOR_UPGRADE", "Not eligible for upgrade"),
    SCOUT_REPORT_DOES_NOT_BELONG_TO_YOU("SCOUT_REPORT_DOES_NOT_BELONG_TO_YOU", "Scout report does not belong to you"),
    MOTHER_SHIP_NOT_IN_UPGRADING("MOTHER_SHIP_NOT_IN_UPGRADING", "Mother ship is not upgrading"),
    NAMESPACE_ITEM_NOT_FOUND("NAMESPACE_ITEM_NOT_FOUND", "Namespace item not found"),
    STORAGE_TYPE_NOT_FOUND("STORAGE_TYPE_NOT_FOUND", "Storage type not found"),
    TYPE_PARAMETER_ITEM_EFFECT_NOT_FOUND("TYPE_PARAMETER_ITEM_EFFECT_NOT_FOUND", "Type parameter item effect not found"),
    CANNOT_SCOUT_THIS_USER("CANNOT_SCOUT_THIS_USER", "Can't scout users"),
    INVALID_ITEM_TYPE("INVALID_ITEM_TYPE", "Invalid item type"),
    CANNOT_FOUND_USER_ITEM("CANNOT_FOUND_USER_ITEM", "Can't found user item"),
    CAN_NOT_USE_ITEM("CANNOT_USE_ITEM", "Can't not use item"),
    INVALID_ITEM_TARGET_TYPE("INVALID_ITEM_TARGET_TYPE", "Item target is in valid"),
    SOME_SCOUT_REPORT_NOT_FOUND("SOME_SCOUT_REPORT_NOT_FOUND", "Some scout report not found"),
    MILITARY_BUILDING_CONFIG_IS_NOT_FOUND("MILITARY_BUILDING_CONFIG_IS_NOT_FOUND", "Military building config not found"),
    ESCORT_SHIP_LEVEL_CONFIG_IS_NOT_FOUND("ESCORT_SHIP_LEVEL_CONFIG_IS_NOT_FOUND", "Escort ship level config is not found"),
    ESCORT_SHIP_IS_IN_OTHER_PROCESS("ESCORT_SHIP_IS_IN_OTHER_PROCESS", "Escort ship is in not other process"),
    ESCORT_SHIP_IS_NOT_IN_UPGRADING("ESCORT_SHIP_IS_NOT_IN_UPGRADING", "Escort ship is not in upgrading"),
    ESCORT_SHIP_IS_NOT_IN_BUILDING("ESCORT_SHIP_IS_NOT_IN_BUILDING", "Escort ship is not in building"),
    CAN_NOT_BUILD_BECAUSE_CONFIG_NOT_FOUND("CAN_NOT_BUILD_BECAUSE_CONFIG_NOT_FOUND", "Can not build because config not found"),
    CAN_NOT_BUILD_BECAUSE_OTHER_SHIP_IS_BUILDING("CAN_NOT_BUILD_BECAUSE_OTHER_SHIP_IS_BUILDING", "Can not build because other ship is building"),
    ESCORT_SHIP_IS_BUILDING("ESCORT_SHIP_IS_BUILDING", "Escort ship is building"),
    ESCORT_SHIP_IS_QUEUEING("ESCORT_SHIP_IS_QUEUEING", "Escort ship is queueing"),
    ESCORT_SHIP_IS_NOT_IN_QUEUEING("ESCORT_SHIP_IS_NOT_IN_QUEUEING", "Escort ship is not in queueing"),
    CAN_NOT_QUEUE_BECAUSE_ALL_SHIP_IS_NOT_IN_BUILDING("CAN_NOT_QUEUE_BECAUSE_ALL_SHIP_IS_NOT_IN_BUILDING",
                                                      "Can not queue because all ship is not in building"),
    AMOUNT_BUILD_SHIP_IS_ILLEGAL("AMOUNT_BUILD_SHIP_IS_ILLEGAL", "Amount build ship is illegal"),
    ITEM_NOT_FOUND("ITEM_NOT_FOUND", "Item not found"),
    SPEED_ITEM_ERROR("SPEED_ITEM_ERROR", "Speed items error"),
    AMOUNT_ESCORT_SHIP_IS_NOT_NULL("AMOUNT_ESCORT_SHIP_IS_NOT_NULL", "Amount escort ship is not null"),
    NOT_TECHNOLOGY_ELIGIBLE_FOR_BUY("NOT_TECHNOLOGY_ELIGIBLE_FOR_BUY", "Not technology eligible for buy"),
    TECHNOLOGY_INVALID("TECHNOLOGY_INVALID", "Technology is invalid"),
    BUILDING_IS_LOCKED("BUILDING_IS_LOCKED", "Building is locked"),
    FEATURE_SCOUT_IS_LOCKED("FEATURE_SCOUT_IS_LOCKED", "Feature scout is locked"),
    CAN_NOT_FOUND_ITEM_EFFECT_IN_SPEED_ITEM("CAN_NOT_FOUND_ITEM_EFFECT_IN_SPEED_ITEM", "Can not found item effect speed item"),
    CANNOT_SCOUT_THIS_YOUR_SHELF("CANNOT_SCOUT_THIS_YOUR_SHELF", "Can not scout your shelf"),
    ESCORT_SHIP_IS_NOT_BUILDING("ESCORT_SHIP_IS_NOT_BUILDING", "Escort ship is not building"),
    UPGRADE_SESSION_TYPE_NOT_FOUND("UPGRADE_SESSION_TYPE_NOT_FOUND", "Upgrade session type not found"),
    TYPE_APPLY_SPEED_ITEM_NOT_FOUND("TYPE_APPLY_SPEED_ITEM_NOT_FOUND", "Type apply item not found"),
    TYPE_ITEM_DOES_NOT_MATCH("TYPE_ITEM_DOES_NOT_MATCH", "Type item does not match"),
    CAN_NOT_UPGRADE_BECAUSE_THE_TECHNOLOGY_IS_NOT_RESEARCHED("CAN_NOT_UPGRADE_BECAUSE_THE_TECHNOLOGY_IS_NOT_RESEARCHED",
                                                             "Can not upgrade because the technology is not researched"),
    YOU_DO_NOT_HAVE_THIS_ITEM("YOU_DO_NOT_HAVE_THIS_ITEM", "You do not have this item"),
    CAN_NOT_USE_SPEED_ITEM("CAN_NOT_USE_SPEED_ITEM", "Can't not use speed item"),
    TECHNOLOGY_TYPE_IS_LOCKED("TECHNOLOGY_TYPE_IS_LOCKED", "Technology type is locked"),
    CAN_NOT_FOUND_TYPE_ITEM_SPEED_APPLY("CAN_NOT_FOUND_TYPE_ITEM_SPEED_APPLY", "Can not found type item speed apply"),
    EFFECT_IS_ACTIVATED("ANTI_SCOUT_IS_ACTIVATED", "Anti scout is activated"),
    PEACE_SHIELD_ACTIVATED("PEACE_SHIELD_ACTIVATED", "Enemy has activated peace shield"),
    USER_ITEM_NOT_FOUND("USER_ITEM_NOT_FOUND", "User item is not found"),

    BOOKMARK_NOT_FOUND("BOOKMARK_NOT_FOUND", "Bookmark is not found"),

    ELEMENT_NOT_FOUND("ELEMENT_NOT_FOUND", "Elements not found"),
    TYPE_ELEMENT_NOT_FOUND("TYPE_ELEMENT_NOT_FOUND", "Type elements not found"),
    ALLIANCE_NOT_FOUND("ALLIANCE_NOT_FOUND", "Alliance is not found"),
    USER_BASE_NOT_FOUND("USER_BASE_NOT_FOUND", "User base is not found"),
    WAR_INFO_NOT_FOUND("WAR_INFO_NOT_FOUND", "War info is not found"),
    USER_NOT_IN_ALLIANCE("USER_NOT_IN_ALLIANCE", "User not in any alliance"),

    NOT_ENOUGH_ACTION_POINT("NOT_ENOUGH_ACTION_POINT", "No Action Point left. Call your ship back to get it back or upgrade Castle to earn more."),
    SEA_ELEMENT_NOT_FOUND("SEA_ELEMENT_NOT_FOUND", "Sea element with provided id is not found"),
    SEA_ACTIVITY_NOT_FOUND("SEA_ACTIVITY_NOT_FOUND", "Sea activity is not found"),
    SOURCE_IS_NOT_ANCHOR("SOURCE_IS_NOT_ANCHOR", "Source position is not an anchor"),
    NO_TROOP_ON_THIS_ELEMENT("NO_TROOP_ON_THIS_ELEMENT", "No troop is found on this sea element"),
    INVALID_DESTINATION("INVALID_DESTINATION", "Invalid destination"),
    LOCATION_IN_USE("LOCATION_IN_USE", "Can not use this location! Location has been used"),
    CAN_NOT_GET_LEVEL("CAN_NOT_GET_LEVEL", "Can not get level"),
    CAN_NOT_FIND_EMPTY_USER_BASE("CAN_NOT_FIND_EMPTY_USER_BASE", "Can't find empty user base"),
    INVALID_COORDINATES("INVALID_COORDINATES", "The location you selected is not valid. Please choose another location"),
    ACTIVITY_ENDED("ACTIVITY_ALREADY_ENDED", "Activity already ended"),
    BOOK_MARK_EXISTED("BOOK_MARK_EXISTED", "Bookmark already existed in chosen position"),
    NEW_LOCATION_IS_REQUIRED("NEW_LOCATION_IS_REQUIRED", "New location is required"),
    ARMY_WITHDREW("ARMY_WITHDREW", "Army has withdrew"),
    MOTHER_SHIP_ALREADY_ON_MISSION("MOTHER_SHIP_ALREADY_ON_MISSION", "Mother ship is on another duty"),
    LINE_UP_ALREADY_ON_MISSION("LINE_UP_ALREADY_ON_MISSION", "Line up is on another duty"),
    NOT_ENOUGH_AMOUNT_OF_ESCORT_SHIP("NOT_ENOUGH_AMOUNT_OF_ESCORT_SHIP", "There is not enough escort ships"),
    INVALID_SEA_ELEMENT("INVALID_SEA_ELEMENT", "Invalid sea element"),
    SHIP_LINE_UP_NOT_FOUND("SHIP_LINE_UP_NOT_FOUND", "Ship lineup is not found"),
    MOTHER_SHIP_CAPACITY_EXCEEDED("MOTHER_SHIP_CAPACITY_EXCEEDED", "Mother ship capacity exceeded limit"),
    CAN_NOT_MOVE_BASE_HAVE_SEA_ACTIVITY("CAN_NOT_MOVE_BASE_HAVE_SEA_ACTIVITY", "You can not move base because you have sea activity"),
    LINE_UP_WAS_ALREADY_DEPLOYED("LINE_UP_WAS_ALREADY_DEPLOYED", "Line up was already deployed"),
    TROOP_MOVEMENT_HISTORY_NOT_FOUND("TROOP_MOVEMENT_HISTORY_NOT_FOUND", "Troop movement history is not found"),
    SCOUT_MISSION_OF_THIS_TYPE_ALREADY_IN_PROGRESS("SCOUT_MISSION_OF_THIS_TYPE_ALREADY_IN_PROGRESS", "This scout mission is in progress"),
    BATTLE_NOT_FOUND("BATTLE_NOT_FOUND", "Battle not found"),
    BATTLE_ROUND_NOT_FOUND("BATTLE_ROUND_NOT_FOUND", "Battle round not found"),
    TROOP_MOVEMENT_TYPE_NOT_SPECIFIED("TROOP_MOVEMENT_TYPE_NOT_SPECIFIED", "Troop movement type was not provided"),
    RESOURCE_ELEMENT_IS_NOT_FOUND("RESOURCE_ELEMENT_IS_NOT_FOUND", "Resource element is not found"),
    BATTLE_REPORT_NOT_FOUND("BATTLE_REPORT_NOT_FOUND", "Battle report not found"),
    ROUND_REPORT_NOT_FOUND("ROUND_REPORT_NOT_FOUND", "Round report not found"),
    BATTLE_PROFILE_NOT_FOUND("BATTLE_PROFILE_NOT_FOUND", "Battle profile not found"),
    CAN_NOT_DELETE_IN_PROGRESS_BATTLE_REPORT("CAN_NOT_DELETE_IN_PROGRESS_BATTLE_REPORT", "Can not delete in progress battle report"),
    CONSUME_MESSAGE_BEFORE_FLUSHING_ENTITY("CONSUME_MESSAGE_BEFORE_FLUSHING_ENTITY", "Wait for entity to be flush to database"),
    CAN_NOT_WITHDRAW("CAN_NOT_WITHDRAW", "Can not withdraw ship line up"),
    CAN_NOT_START_BATTLE_WHEN_HAVE_OTHER("CAN_NOT_START_BATTLE_WHEN_HAVE_OTHER", "Cannot start liberate combat when other fight happens on base"),
    FEATURE_COMING_SOON("FEATURE_COMING_SOON", "Feature is coming soon"),
    CAN_NOT_JOIN_BATTLE("CAN_NOT_JOIN_BATTLE", "Can not join battle"),
    ENEMY_IS_BEING_ATTACKED_BY_OTHER_USERS("ENEMY_IS_BEING_ATTACKED_BY_OTHER_USER", "Enemy is being attack. Can not start new battle"),
    CAN_NOT_USE_MOVE_BASE_ITEM_WHEN_IN_COMBAT("CAN_NOT_USE_ITEM_AT_MOMENT", "You cannot move your base when mother ship is on duty"),
    BATTLE_IS_END("BATTLE_IS_END", "Battle is ended"),
    ALREADY_SENT_TROOP_ON_ATTACKING_MISSION("ALREADY_SENT_TROOP_ON_ATTACKING_MISSION", "You've already sent troop to target"),
    FLAT_CHECK_RESULT_BATTLE_NOT_FOUND("FLAT_CHECK_RESULT_BATTLE_NOT_FOUND", "Flat check result battle not found"),
    USER_HAS_YET_TO_JOIN_BATTLE("USER_HAS_YET_TO_JOIN_BATTLE", "Send troop to join battle"),
    BOSS_IS_ATTACKED("BOSS_IS_ATTACKED", "Boss is attacked"),
    NOTIFICATION_TEMPLATE_NOT_FOUND("NOTIFICATION_TEMPLATE_NOT_FOUND", "Notification template is not found"),
    NOTIFICATION_NAMED_PARAM_MISSING("NOTIFICATION_NAMED_PARAM_MISSING", "Notification named param is missing"),
    MESSAGE_QUEUE_DATA_TYPE_MISMATCH("MESSAGE_QUEUE_DATA_TYPE_MISMATCH", "Message queue data type is mismatched"),
    ACTIVITY_MISSION_NOT_SPECIFIED("ACTIVITY_MISSION_NOT_SPECIFIED", "Mission type is required to start activity"),
    CAN_NOT_STATION_ON_TARGET("CAN_NOT_STATION_ON_TARGET", "Send troop to occupy target first"),
    BATTLE_TYPE_NOT_FOUND("BATTLE_TYPE_NOT_FOUND", "Battle type not found"),
    IN_PROGRESS_LIBERATING("IN_PROGRESS_LIBERATING", "in process liberating"),
    ELEMENT_IS_UNOCCUPIED("ELEMENT_IS_UNOCCUPIED", "Element is unoccupied"),
    UPGRADE_SESSION_IS_DONE("UPGRADE_SESSION_IS_DONE", "Upgrade session is done"),
    MANY_ELEMENT_IN_COORDINATES("MANY_ELEMENT_IN_COORDINATES", "many element in coordinates"),
    CAN_NOT_TELEPORT_WHEN_BASE_OCCUPIED("CAN_NOT_TELEPORT_WHEN_BASE_OCCUPIED", "Can not teleport when base is occupied"),
    ENEMY_BUILDING_IS_LOCKED("ENEMY_BUILDING_IS_LOCKED", "Enemy building is locked"),
    CANNOT_BUY_THIS_MOTHER_SHIP("CANNOT_BUY_THIS_MOTHER_SHIP", "Can not buy this mother ship");

    private static final Map<String, ErrorCode> MAPPER;

    static {
        MAPPER = Arrays.stream(values()).collect(Collectors.toMap(ErrorCode::getMessage, Function.identity()));
    }

    @JsonCreator
    public static ErrorCode of(String value) {
        return MAPPER.get(StringUtils.deleteWhitespace(value.toUpperCase()));
    }

    private String code;
    private String message;
}
