FROM openjdk:11

WORKDIR ~/kos-admin
COPY ./admin-app/target/admin-app-0.0.1-SNAPSHOT.jar ./
COPY ./firebase-secret-key.json ./
COPY ./VERSION.txt ./
COPY ./CHANGELOG.txt ./

ENV JAVA_TOOL_OPTIONS -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
CMD ["java", "-Dspring.profiles.active=staging", "-jar", "./admin-app-0.0.1-SNAPSHOT.jar"]