package com.supergroup.kos.building.domain.constant;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ItemConfigKey {
    QUEEN_CONFIG("QUEEN_CONFIG"),
    RELIC_CONFIG("RELIC_CONFIG"),
    WEAPON_CONFIG("WEAPON_CONFIG"),
    WEAPON_SET_CONFIG("WEAPON_SET_CONFIG"),
    WEAPON_SET_LEVEL_CONFIG("WEAPON_SET_LEVEL_CONFIG"),
    ESCORT_SHIP_GROUP_CONFIG("ESCORT_SHIP_GROUP_CONFIG"),
    ESCORT_SHIP_GROUP_LEVEL_CONFIG("ESCORT_SHIP_GROUP_LEVEL_CONFIG"),
    ESCORT_SHIP_CONFIG("ESCORT_SHIP_CONFIG"),
    ESCORT_SHIP_LEVEL_CONFIG("ESCORT_SHIP_LEVEL_CONFIG"),
    MOTHER_SHIP_LEVEL_CONFIG("MOTHER_SHIP_LEVEL_CONFIG"),
    MOTHER_SHIP_QUALITY_CONFIG("MOTHER_SHIP_QUALITY_CONFIG"),
    MOTHER_SHIP_SYSTEM_CONFIG("MOTHER_SHIP_SYSTEM_CONFIG");


    private String itemConfigKey;

}
