server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    "liquibase": INFO
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
      file-size-threshold: 2KB
      enabled: true
  datasource:
    url: jdbc:postgresql://27.72.98.184:1232/kos
    username: kos
    password: kos!1@
  rabbitmq:
    host: localhost
    port: 5672
    username: kos
    password: kos
auth:
  cache:
    timeout: 5
webview:
  link: ${RG_WEBSITE_URL}
sendgrid:
  masterEmail: supertech.dev123@gmail.com
  token: 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
website-url: https://marketplaceradiantgalaxy.sute.dev
default-avatar: https://storage.googleapis.com/gateplay-public-bucket/dev/avatar/Account_Panel_AvartarDefaul.png
jwt:
  secret: mysecretttttttttttttttttttttttttttttttttttttttttttttttt
  expiry:
    verify-session: 10
    access:
      user: 5000
      admin: 480
verify-session:
  timeout: 10
  period: 10
  register:
    attempts: 3
login-session:
  timeout: 10
login:
  attempts: 5
  lock-time-duration: 5
redis:
  host: localhost
  port: 6379
app:
  firebase-configuration-file: messenger-5c285-firebase-adminsdk-r382b-1676b91f01.json
do:
  space:
    key: 7BKBQJSQBTXUU5XV4E3K
    secret: RnlL9zBiI09rOWhUy6e+sASG5sEJngVg8owMAsNAChI
    endpoint: sgp1.digitaloceanspaces.com
    region: sgp1
    bucket: kingofsea
sentry:
  dsn: https://b30b921e0773494b9f59972735f386fd@o1383702.ingest.sentry.io/6701143
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0
  environment: dev
telegram:
  bot:
    token: 5479185678:AAHSEzMWnWF2nb2p9n7On__wSgiKTRfakjg
